SET IDENTITY_INSERT [dbo].[Artists] ON
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (408, N'Топлесс', 78650189, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (409, N'2 Brothers On The 4th Floor', 70147468, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (410, N'2 For good', 72549465, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (411, N'2 Raff', 72548567, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (412, N'2 Unlimited', 66998187, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (413, N'3-O-Matic', 72548585, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (414, N'140 Ударов в минуту', 74497471, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (415, N'666', 34353897, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (416, N'Adriano Celentano', 74343834, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (417, N'Alice DeeJay', 75578529, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (418, N'Alphavile', 77989247, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (419, N'Arabesque', 70776835, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (420, N'Army of lovers', 72549032, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (421, N'Alexia', 74497747, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (422, N'Afric Simone', 77989044, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (423, N'ATB', 67000485, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (424, N'ATC', 70147419, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (425, N'ABBA', 35990591, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (426, N'Activate', 77989222, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (427, N'Aqua', 28762794, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (428, N'Alizee', 72549067, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (429, N'Ace of base', 28761870, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (430, N'Baccara', 71087431, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (431, N'Barcode Brothers', 72549491, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (432, N'Backstreet Boys', 77989531, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (433, N'Basement Jaxx', 77989315, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (434, N'B.G.The Prince Of Rap', 77989225, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (435, N'Biraytrax', 77989155, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (436, N'Bellini', 77989272, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (437, N'Britney Spears', 77893556, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (438, N'B.B.E.', 77893013, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (439, N'Brad Fiedel', 77989519, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (440, N'BT', 75578507, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (441, N'Becca', 72548844, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (442, N'Blur', 72549055, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (443, N'Blümchen', 70147443, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (444, N'Boney M', 36096673, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (445, N'Bon Jovi', 70501670, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (446, N'Bad boys blue', 34999382, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (447, N'Brooklyn Bounce', 77988821, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (448, N'Bill Conti', 70147348, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (449, N'Captain Hollywood', 77989541, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (450, N'Capella', 77989093, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (451, N'Cabballero', 77989170, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (452, N'С.C. Catch', 70500475, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (453, N'C-Block', 77989462, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (454, N'Captain jack', 70147526, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (455, N'Ce Ce Peniston', 77989422, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (456, N'Corona', 70147575, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (457, N'Coolio', 77988923, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (458, N'Centory', 77989172, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (459, N'Cliff Wedge', 77988960, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (460, N'Cher', 77989269, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (461, N'Culture Beat', 70147584, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (462, N'Crush', 77989339, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (463, N'Cappella', 70209304, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (464, N'Benny Benassi', 36626423, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (465, N'Das Modul', 77989133, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (466, N'Darude', 72548782, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (467, N'Darkness', 77989096, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (468, N'Da Blitz', 77989182, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (469, N'Del Shannon', 78222079, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (470, N'Dilated Peoples', 77989104, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (471, N'Dolphin''s Mind', 77988859, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (472, N'Double Vision', 77989126, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (473, N'Dschinghis Khan', 72004250, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (474, N'Decadance', 77989100, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (475, N'Demis Roussos', 71546859, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (476, N'Deep Purple', 77988967, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (477, N'Depeche Mode', 70104451, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (478, N'DJ Грув', 75578860, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (479, N'DJ Цветкоff', 77988785, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (480, N'DJ Quicksilver', 77893889, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (481, N'DJ DyeLb4uk', 70500870, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (482, N'Dr. Alban', 28948653, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (483, N'DJ Pierro', 74631900, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (484, N'DJ Bobo', 28948526, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (485, N'DJ Aligator', 28762830, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (486, N'Deee-Lite', 77989434, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (487, N'David Guetta', 28948490, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (488, N'Double You', 77989210, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (489, N'Dolls United', 77989142, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (490, N'Dune', 77989119, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (491, N'Elektrik Cokernut', 77989039, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (492, N'Elton John', 77989233, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (493, N'EMF', 77989426, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (494, N'Enigma', 76987745, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (495, N'Eiffel 65', 70147156, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (496, N'E-Rotic', 28762510, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (497, N'E-Type', 28949157, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (498, N'Evanescence', 70104401, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (499, N'Europe', 70147622, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (500, N'Eurythmics', 77988882, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (501, N'Euphoric', 77989123, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (502, N'Finger and Kadel', 77989501, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (503, N'Fun Fun', 72188620, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (504, N'Fun Factory', 70209386, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (505, N'Future Breeze', 77989057, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (506, N'Gala', 77892983, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (507, N'Gigi D''Agostino', 77989227, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (508, N'General Base', 77988810, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (509, N'Hi-Fi', 28948474, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (510, N'Hi-Gate', 77989054, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (511, N'Haddaway', 28909813, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (512, N'Ice MC', 70147371, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (513, N'Intermission', 77989472, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (514, N'Imperio', 72548549, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (515, N'J.K.', 72548180, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (516, N'Joy', 70517364, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (517, N'Keanu Silva', 77989001, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (518, N'Kai Tracid', 77988900, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (519, N'Kate Ryan', 77988847, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (520, N'Kosmonova', 72549507, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (521, N'K. Da ''Cruz', 77989446, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (522, N'Kernkraft 4000', 74454525, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (523, N'Kraftwerk', 70500570, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (524, N'Klubbheads', 70501665, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (525, N'Lisa Marie Experience', 72548225, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (526, N'La Bouche', 72548113, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (527, N'La Cream', 77989165, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (528, N'LeAnn Rimes', 77988838, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (529, N'Loft', 77989024, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (530, N'Lisette Melendez', 77989334, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (531, N'Livin Joy', 77989399, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (532, N'Linkin park', 28948564, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (533, N'Le Click', 77988817, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (534, N'Los Del Mar', 77989277, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (535, N'Max-A-Million', 77989320, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (536, N'Mabel', 77989185, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (537, N'Maxx', 69027213, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (538, N'Mario Piu', 77989146, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (539, N'Mighty Dub Katz', 77892976, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (540, N'Mattafix', 77894006, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (541, N'Mo-do', 72549023, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (542, N'Modern Talking', 28761897, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (543, N'Masterboy', 28762817, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (544, N'Moby', 66806002, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (545, N'Miranda', 77988898, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (546, N'Madonna', 70209432, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (547, N'Michael Jackson', 36212909, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (548, N'Milk Inc.', 77989082, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (549, N'Mr. President', 68297688, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (550, N'Melani C', 72549084, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (551, N'Melodie Mc', 77988913, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (552, N'Music Instructor', 77988873, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (553, N'Mylène Farmer', 70784935, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (554, N'Mystikal', 77989106, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (555, N'Nana', 77989568, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (556, N'Nate Dogg', 77989103, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (557, N'Narcotic Thrust', 70147186, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (558, N'Nina', 77989215, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (559, N'Nightcrawlers', 77989369, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (560, N'Nirvana', 28948455, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (561, N'N-Trance', 77989019, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (562, N'N Sync', 72548748, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (563, N'Oomph!', 66806240, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (564, N'Opus', 28948850, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (565, N'Object One', 77988790, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (566, N'Patty Ryan', 77989352, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (567, N'Planet soul', 77989442, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (568, N'Porn Kings', 77989188, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (569, N'Paul Johnson', 77989535, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (570, N'Papa Roach', 76154896, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (571, N'Paffendorf', 72548193, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (572, N'Propellerheads', 77989502, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (573, N'Pendulum', 75708835, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (574, N'Pearl', 77988907, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (575, N'Pink Floyd', 71087679, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (576, N'Paradiso', 70501588, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (577, N'Pin-Occhio', 77989066, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (578, N'Pharao', 77989071, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (579, N'Push', 74631972, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (580, N'Queen', 34546678, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (581, N'Rammstein', 34937782, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (582, N'Real McCoy', 77989417, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (583, N'Rob Dougan', 77989419, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (584, N'RMB', 77989140, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (585, N'Reel 2 Real', 77989522, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (586, N'Rednex', 72548869, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (587, N'Red Hot Chili Peppers', 70147309, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (588, N'Roxette', 70105785, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (589, N'Robert Miles', 28949070, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (590, N'Rollergirl', 77988879, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (591, N'Robin S', 77989089, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (592, N'R.O.O.S.', 77988850, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (593, N'Sash!', 70105803, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (594, N'Saphir', 75578652, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (595, N'Space', 71546842, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (596, N'Slam', 77989194, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (597, N'Silent Circle', 70339742, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (598, N'Secret Service', 69035987, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (599, N'Samantha Fox', 71836042, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (600, N'Sm-Trax', 77989005, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (601, N'Southside Spinners', 77989151, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (602, N'Solid Base', 72548857, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (603, N'Stardust', 77989386, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (604, N'Sandra', 28948584, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (605, N'Sabrina', 28948996, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (606, N'Snap', 28949048, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (607, N'Scooter', 28761831, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (608, N'Scotch', 71836051, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (609, N'Skillet', 66806325, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (610, N'Spike', 77989459, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (611, N'Sunbeam', 72548507, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (612, N'Souladelic', 75578800, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (613, N'SQEEZER', 77988997, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (614, N'System F', 72548137, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (615, N'Sylver', 77989055, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (616, N'Tag Team', 77989157, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (617, N'Terra Blvck', 77989079, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (618, N'Tina Turner', 70501386, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (619, N'Tom Wilson', 77989544, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (620, N'Toy-Box', 72549092, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (621, N'Toni Braxton', 70500922, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (622, N'Technotronic', 72549004, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (623, N'TELEX', 70500646, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (624, N'Texture', 77989014, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (625, N'Tiёsto', 70104512, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (626, N'Twenty 4 Seven', 70209381, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (627, N'T.H. Express', 77989018, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (628, N'The Chemical Brothers', 77988951, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (629, N'The Sax Brothers', 77989012, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (630, N'The Immortals', 77989509, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (631, N'The Rasmus', 77989329, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (632, N'The Sunclub', 77988796, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (633, N'The Course', 77893001, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (634, N'The Offspring', 70501703, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (635, N'The Outhere Brothers', 77989364, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (636, N'The Eagles', 76352160, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (637, N'The Prodigy', 28762839, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (638, N'The Rolling Stones', 75578581, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (639, N'THE BUCKETHEADS', 72548620, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (640, N'The Beloved', 77989128, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (641, N'The Klf', 77989348, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (642, N'Teach-In', 70618527, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (643, N'The Cardigans', 72549038, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (644, N'The Beatles', 37953563, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (645, N'U96', 77988805, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (646, N'Unique II', 77989477, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (647, N'Ultra Nate', 77989381, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (648, N'Umberto Tozzi', 77989060, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (649, N'Vengaboys', 72548359, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (650, N'VideoKids', 74844624, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (651, N'Watergate', 77988977, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (652, N'Whigfield', 77988954, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (653, N'Yamboo', 77989450, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (654, N'Zhi-Vago', 74497624, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (655, N'X-MODE', 77989355, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (656, N'X-Perience', 75183883, 1)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (657, N'Аида Ведищева', 75578849, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (658, N'Александр Добрынин', 77989495, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (659, N'Александр Айвазов', 75579450, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (660, N'Александр Буйнов', 72549448, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (661, N'Аркадий Укупник', 72548252, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (662, N'Александр Розенбаум', 75579085, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (663, N'Алсу', 70209367, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (664, N'Анна Герман', 75578831, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (665, N'Анонс', 70501636, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (666, N'А.Серов', 74497827, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (667, N'Агата Кристи', 28762851, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (668, N'Алла Пугачева', 70105848, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (669, N'Ангина', 28761958, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (670, N'Акула', 28761925, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (671, N'Алексин', 28761798, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (672, N'Андрей Губин', 28762806, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (673, N'Братья Грим', 66806030, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (674, N'Божья коровка', 36029827, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (675, N'Белый орёл', 28948679, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (676, N'Банда Андрюха', 30362187, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (677, N'Балаган Лимитед', 65072939, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (678, N'Банд''эрос', 77548688, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (679, N'Браво', 72548537, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (680, N'Блестящие', 70209296, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (681, N'Валентина Легкоступова', 77989254, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (682, N'Валерия', 70209452, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (683, N'Валерий Сюткин', 72549132, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (684, N'Вадим Казаченко', 77988941, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (685, N'Високосный Год', 77988827, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (686, N'Владимир Макаров', 75578940, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (687, N'Владимир Маркин', 74497930, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (688, N'Влад Сташевский', 75579270, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (689, N'Валерий Леонтьев', 75579244, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (690, N'Вячеслав Быков', 74497559, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (691, N'Валерий Залкин', 70209464, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (692, N'Виагра', 74296076, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (693, N'ВИА "Самоцветы"', 74497393, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (694, N'Верка Сердючка', 70209325, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (695, N'Вирус', 28761681, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (696, N'Валерий Меладзе', 43428768, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (697, N'Владимир Высоцкий', 38267125, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (698, N'Голубые Береты', 72548736, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (699, N'Горячие Головы', 75578338, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (700, N'Гости из будущего', 28762055, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (701, N'Глюк''oZa', 67613859, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (702, N'Гарик Сукачёв', 37257830, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (703, N'Демо', 28761749, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (704, N'Децл', 35606861, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (705, N'Дискомафия', 77989289, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (706, N'ДДТ', 34652114, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (707, N'Дмитрий Маликов', 70104595, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (708, N'Дюна', 28949114, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (709, N'Данко', 74454611, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (710, N'Евро', 28761739, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (711, N'Евгений Осин', 72548720, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (712, N'Евгений Белоусов', 28948943, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (713, N'Жасмин', 72549371, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (714, N'Жуки', 70104476, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (715, N'Звери', 31159525, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (716, N'За-За', 70501575, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (717, N'Земляне', 74497503, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (718, N'Земфира', 28761877, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (719, N'Иван Купала', 77989598, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (720, N'Игорь Николаев', 75579147, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (721, N'Игорёк', 28949094, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (722, N'Иосиф Кобзон', 75579155, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (723, N'Игорь Скляр', 75578962, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (724, N'Ирина Аллегрова', 70500914, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (725, N'Ирина Салтыкова', 28948898, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (726, N'Иванушки International', 28761765, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (727, N'Кабаре-дуэт Академия', 77989090, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (728, N'Катя Чехова', 75579284, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (729, N'Карт-бланш', 77989575, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (730, N'Катя Лель', 74454622, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (731, N'Комиссар', 74497486, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (732, N'Корни', 74497837, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (733, N'Кай Метов', 74497549, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (734, N'Краски', 28761653, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (735, N'Кристина Corp.', 74497755, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (736, N'Кармен', 28949020, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (737, N'Комбинация', 28948780, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (738, N'Лада Денс', 70501597, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (739, N'Любэ', 33730602, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (740, N'Лицей', 70501497, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (741, N'Лев Лещенко', 74497943, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (742, N'Лика', 74497408, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (743, N'Ленинград', 36494745, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (744, N'Ляпис Трубецкой', 28761719, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (745, N'Леприконсы', 28948689, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (746, N'М. Муромов', 77989113, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (747, N'Mr.Credo', 74497537, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (748, N'Маленький Принц', 71150604, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (749, N'Мальчишник', 75538373, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (750, N'Марина Хлебникова', 74497912, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (751, N'МакSим', 70501677, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (752, N'Машина времени', 34353786, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (753, N'Михаил Гребенщиков', 77989514, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (754, N'Михаил Боярский', 70147273, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (755, N'Михаил Круг', 37289269, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (756, N'МинНет', 70501545, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (757, N'Михаил Шуфутинский', 36664905, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (758, N'Мираж', 70105824, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (759, N'Мумий тролль', 33303465, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (760, N'Мурат Насыров', 74497463, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (761, N'Наталья Власова', 77989359, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (762, N'Наталья Ветлицкая', 75578905, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (763, N'Наташа Королёва', 72549397, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (764, N'Натали', 70147241, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (765, N'На-На', 28948962, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (766, N'Непара', 75579413, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (767, N'Неигрушки', 74268438, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (768, N'Нэнси', 28762019, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (769, N'Nautilus Pompilius', 28762149, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (770, N'Оскар', 77989563, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (771, N'Океан Ельзы', 75020550, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (772, N'Оловянные солдатики', 75578911, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (773, N'Олег Газманов', 37699074, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (774, N'Отпетые мошенники', 28762132, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (775, N'Парк Горького', 74497526, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (776, N'Планка', 70501557, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (777, N'Поль Мориа', 74251901, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (778, N'ППК', 66806301, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (779, N'Песняры', 70500960, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (780, N'Премьер-министр', 28948800, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (781, N'Пропаганда', 28761887, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (782, N'Револьверс', 77988893, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (783, N'Рождество', 70147668, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (784, N'Русский размер', 36070903, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (785, N'Reflex', 28762550, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (786, N'Руки вверх', 28761519, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (787, N'С. Рерих', 77989394, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (788, N'Саша Project', 77989296, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (789, N'София Ротару', 70147215, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (790, N'Светлана Разина', 75579398, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (791, N'Сектор газа', 28761755, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (792, N'Света', 28761701, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (793, N'Стас Михайлов', 72549515, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (794, N'Стрелки', 28761843, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (795, N'Сплин', 28762033, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (796, N'Танцы минус', 70501651, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (797, N'Турбомода', 54694622, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (798, N'Татьяна Буланова', 28948929, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (799, N'Тутси', 77548660, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (800, N'Тату', 28761808, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (801, N'Технология', 71637686, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (802, N'Татьяна Овсиенко', 70501606, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (803, N'УмаТурман', 70209400, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (804, N'Фабрика', 54812634, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (805, N'Фактор 2', 35899512, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (806, N'Филипп Киркоров', 72549430, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (807, N'Фристайл', 28948820, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (808, N'Чайф', 28949123, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (810, N'Чичерина', 70501431, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (811, N'Шура', 28762091, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (812, N'Электроклуб', 75579383, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (813, N'Юрий Антонов', 28762096, 0)
INSERT INTO [dbo].[Artists] ([ArtistId], [Name], [AlbumVkId], [LanguageArtistId]) VALUES (814, N'Юрий Шатунов', 28761943, 0)
SET IDENTITY_INSERT [dbo].[Artists] OFF
